/**
 * Vocabulário fechado de códigos de erro da API. O código é o contrato com o
 * cliente: o app traduz `code` (+ `params`) para o idioma do usuário; a
 * mensagem nunca é renderizada. Adicionar um erro novo = adicionar o código
 * aqui + a copy no app.
 */
export const ERROR_CODES = [
  // Autenticação e sessão
  'AUTH_REQUIRED',
  'SESSION_INVALID',
  'INVALID_CREDENTIALS',
  'INVALID_PASSWORD',
  'INVALID_REFRESH_TOKEN',
  'INVALID_VERIFICATION_CODE',
  'ACCOUNT_BANNED',
  'ACCOUNT_SUSPENDED',
  'ACCOUNT_ANONYMIZED',
  'PASSWORD_REQUIRED',

  // MFA
  'INVALID_MFA_CODE',
  'MFA_ALREADY_ENABLED',
  'MFA_SETUP_NOT_STARTED',
  'MFA_ADMIN_ONLY',
  'MFA_ENROLLMENT_SCOPE',

  // Login social
  'INVALID_PROVIDER_TOKEN',
  'SOCIAL_EMAIL_UNVERIFIED',
  'SOCIAL_EMAIL_PERMISSION_REQUIRED',
  'SOCIAL_PROVIDER_MISCONFIGURED',
  'SOCIAL_PROVIDER_UNAVAILABLE',
  'SOCIAL_USER_MISSING',
  'USERNAME_GENERATION_FAILED',

  // Autorização / gates
  'FORBIDDEN',
  'ADMIN_ONLY',
  'PREMIUM_REQUIRED',
  'PRIVATE_PROFILE',
  'LOCATION_CONSENT_REQUIRED',
  'NOT_PROFILE_OWNER',
  'CANNOT_MODERATE_ADMIN',
  'SELF_MODERATION',

  // Cadastro / identidade (409 com `field`)
  'EMAIL_TAKEN',
  'USERNAME_TAKEN',
  'PHONE_TAKEN',
  'DUPLICATE_VALUE',

  // Validação
  'VALIDATION_ERROR',
  'INVALID_CURSOR',
  'INVALID_IDEMPOTENCY_KEY',
  'INVALID_URL',
  'URL_HOST_NOT_ALLOWED',

  // Entidades não encontradas
  'USER_NOT_FOUND',
  'EVENT_NOT_FOUND',
  'SPOT_NOT_FOUND',
  'POST_NOT_FOUND',
  'COMMENT_NOT_FOUND',
  'PARENT_COMMENT_NOT_FOUND',
  'MESSAGE_NOT_FOUND',
  'CONVERSATION_NOT_FOUND',
  'REACTION_NOT_FOUND',
  'REPORT_NOT_FOUND',
  // Denúncia anterior ao recurso de evidência, ou prova já expurgada pela
  // retenção: distinto de REPORT_NOT_FOUND, que é a denúncia não existir.
  'REPORT_EVIDENCE_NOT_FOUND',
  // Apagar a denúncia apagaria (por cascade) a prova cifrada que sustenta uma
  // punição já aplicada. Levante a punição antes, se a intenção for essa.
  'REPORT_BACKS_ACTIVE_PUNISHMENT',
  'NOTIFICATION_NOT_FOUND',
  'SERIES_NOT_FOUND',
  'PROMOTION_NOT_FOUND',
  'ATTENDANCE_NOT_FOUND',
  'BLOCK_NOT_FOUND',
  'FOLLOW_NOT_FOUND',
  'FOLLOWER_NOT_FOUND',
  'FOLLOW_REQUEST_NOT_FOUND',
  'PARTICIPANT_NOT_FOUND',
  'PLACE_NOT_FOUND',
  'CONSENT_NOT_FOUND',
  'CONSENT_EXPORT_EMPTY',
  'SUBSCRIPTION_NOT_FOUND',
  'VIDEO_NOT_FOUND',
  'INVITE_LINK_NOT_FOUND',

  // Social (follow/block)
  'SELF_FOLLOW',
  'SELF_BLOCK',
  'ALREADY_BLOCKED',
  'ALREADY_FOLLOWING',
  'FOLLOW_REQUEST_ALREADY_SENT',
  'FOLLOW_REQUEST_PROCESSED',

  // Eventos, séries e destaques
  'NOT_EVENT_AUTHOR',
  'NOT_SERIES_AUTHOR',
  'EVENT_ACCESS_DENIED',
  'NO_USERS_TO_INVITE',
  'END_DATE_BEFORE_START',
  'STARTS_AT_IN_PAST',
  'SERIES_ALREADY_CANCELED',
  'EVENT_CANCELED',
  'EVENT_ENDED',
  // 410: o link existiu mas não vale mais — códigos distintos para a copy do
  // app diferenciar "expirou" de "o autor revogou".
  'INVITE_LINK_EXPIRED',
  'INVITE_LINK_REVOKED',
  'PROMOTION_ALREADY_CANCELED',
  'PROMOTION_OVERLAP',
  'PROMOTION_TOO_LONG',
  'MONTHLY_PROMOTION_LIMIT',
  'SUBCATEGORY_INCOHERENT',

  // Spots
  'SPOT_NO_PREFERENCES',
  'SPOT_RADIUS_TOO_LARGE',
  'RADIUS_TOO_LARGE',
  'NOT_SPOT_CREATOR',
  'SPOT_INACTIVE',
  'SPOT_CANCELED',
  'SPOT_FRIENDS_ONLY',
  'SPOT_WINDOW_TOO_LONG',
  'ACTIVE_SPOT_LIMIT',
  'ENDS_AT_IN_PAST',
  'ENDS_AT_AFTER_EVENT_DATE',
  'FRIENDS_FILTER_REQUIRES_AUTH',
  'DAILY_LIMIT_REACHED',

  // Chat
  'NOT_CONVERSATION_MEMBER',
  'CONVERSATION_FORBIDDEN',
  'CONVERSATION_READ_ONLY',
  'INVALID_CONVERSATION',
  'GROUP_ONLY_OPERATION',
  'GROUP_NEEDS_PARTICIPANT',
  'ALREADY_MEMBER',
  'USE_LEAVE_GROUP',
  'NOT_MESSAGE_AUTHOR',
  'MESSAGE_DELETED',
  'MESSAGE_NOT_EDITABLE',
  'SYSTEM_MESSAGE_IMMUTABLE',
  'INVALID_REPLY_MESSAGE',
  'VIDEO_NOT_IN_CONVERSATION',

  // Posts e comentários
  'NOT_POST_AUTHOR',
  'NOT_COMMENT_AUTHOR',
  'COMMENT_REPLY_DEPTH',
  'POST_IMAGE_LIMIT',

  // Denúncias / moderação
  'SELF_REPORT',
  'REPORT_ALREADY_OPEN',
  'REPORT_NOT_ABOUT_USER',
  'REPORTED_CONTENT_GONE',
  'INVALID_REPORT_ACTION',
  'USER_ALREADY_BANNED',

  // Mídia / uploads
  'IMAGE_REQUIRED',
  'AUDIO_REQUIRED',
  'INVALID_IMAGE',
  'INVALID_AUDIO_CONTENT',
  'INVALID_WAVEFORM',
  'UNSUPPORTED_IMAGE_FORMAT',
  'UNSUPPORTED_AUDIO_FORMAT',
  'UNSUPPORTED_VIDEO_FORMAT',
  'FILE_TOO_LARGE',
  'STORAGE_QUOTA_EXCEEDED',
  'INVALID_AUDIO_METADATA',
  'INVALID_VIDEO_METADATA',
  'VIDEO_UPLOAD_REQUIRES_R2',

  // Push
  'INVALID_PUSH_TOKEN',

  // Billing
  'SUBSCRIPTION_ALREADY_ACTIVE',
  'SUBSCRIPTION_NOT_CANCELING',
  'BILLING_CUSTOMER_MISSING',
  'BILLING_PRICE_MISCONFIGURED',
  'BILLING_GATEWAY_UNAVAILABLE',
  'INVALID_SIGNATURE',
  'MISSING_STRIPE_SIGNATURE',

  // Spotify (conta vinculada)
  'SPOTIFY_NOT_LINKED',
  'SPOTIFY_ACCOUNT_IN_USE',
  'SPOTIFY_SCOPE_MISSING',
  'SPOTIFY_RATE_LIMITED',

  // Places
  'PLACES_INVALID_RESPONSE',
  'PLACES_REQUEST_FAILED',
  'PLACES_UNAVAILABLE',

  // Infra
  'COMMENT_SCOPE_MISSING',
  'EMAIL_SEND_FAILED',
  'INTERNAL_ERROR',
] as const

export type ErrorCode = (typeof ERROR_CODES)[number]
